<?php

/**
 * @file
 * @todo what does this file do?
 */

/**
 * Implements hook_form_alter().
 *
 * Alters the display of the node/add form for the Timesheets
 */
function cehs_ts_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  $uid = $user->uid;
  $account = user_load($uid);
  
  $profile = profile2_load_by_user($account);
  
  $employee_name = ''; // Set variable to NULL initially.
  if (profile2_load_by_user($account, 'payroll_profile')) { // Check if main profile exists
    $name = field_get_items('profile2', $profile['payroll_profile'], 'field_payroll_name');
    $first = $name[0]['safe']['given'];
    $middle = $name[0]['safe']['middle'];
    $last = $name[0]['safe']['family'];
    $suff = $name[0]['safe']['generational'];
    
    $full_name = implode(' ', array($first, $middle, $last, $suff));
    $employee_name = trim(preg_replace('/\s+/', ' ', $full_name));
  };
  
  $employee_id = ''; // Set variable to NULL initially.
  if (profile2_load_by_user($account, 'payroll_profile')) { // Check if payroll profile exists
    $employee_id_raw = field_get_items('profile2', $profile['payroll_profile'], 'field_um_id');
    $employee_id = $employee_id_raw[0]['value'];
  };
  
  // switch will let us use different alters for each of the three timesheet forms
  switch ($form_id) {
    case 'ts_biweekly_node_form': 
      if (empty($form_state['values']['title'])) {
        $form['title']['#default_value'] = 'CEHS Timesheet';
      };
      
      $form['title']['#disabled'] = TRUE;
      
      if ($form['field_employee_approval']['und']['#default_value'] == 0) {
        $form['field_employee_name']['und']['0']['value']['#default_value'] = $employee_name;
        $form['field_employee_id']['und']['0']['value']['#default_value'] = $employee_id;
      }
      
      $form['field_employee_name']['#disabled'] = TRUE;
      
      $form['field_employee_id']['#disabled'] = TRUE;
      
      $form['field_r01']['und']['0']['value']['#title'] = '';
      $form['field_r01']['und']['0']['value']['#size'] = '2';
      $form['field_r02']['und']['0']['value']['#title'] = '';
      $form['field_r02']['und']['0']['value']['#size'] = '2';
      $form['field_r03']['und']['0']['value']['#title'] = '';
      $form['field_r03']['und']['0']['value']['#size'] = '2';
      $form['field_r03']['#disabled'] = TRUE;
      $form['field_r04']['und']['0']['value']['#title'] = '';
      $form['field_r04']['und']['0']['value']['#size'] = '2';
      $form['field_r04']['#disabled'] = TRUE;
      $form['field_r05']['und']['0']['value']['#title'] = '';
      $form['field_r05']['und']['0']['value']['#size'] = '2';
      $form['field_r06']['und']['0']['value']['#title'] = '';
      $form['field_r06']['und']['0']['value']['#size'] = '2';
      $form['field_r07']['und']['0']['value']['#title'] = '';
      $form['field_r07']['und']['0']['value']['#size'] = '2';;
      $form['field_r08']['und']['0']['value']['#title'] = '';
      $form['field_r08']['und']['0']['value']['#size'] = '2';
      $form['field_r09']['und']['0']['value']['#title'] = '';
      $form['field_r09']['und']['0']['value']['#size'] = '2';
      $form['field_r10']['und']['0']['value']['#title'] = '';
      $form['field_r10']['und']['0']['value']['#size'] = '2';
      $form['field_r10']['#disabled'] = TRUE;
      $form['field_r11']['und']['0']['value']['#title'] = '';
      $form['field_r11']['und']['0']['value']['#size'] = '2';
      $form['field_r11']['#disabled'] = TRUE;
      $form['field_r12']['und']['0']['value']['#title'] = '';
      $form['field_r12']['und']['0']['value']['#size'] = '2';
      $form['field_r13']['und']['0']['value']['#title'] = '';
      $form['field_r13']['und']['0']['value']['#size'] = '2';
      $form['field_r14']['und']['0']['value']['#title'] = '';
      $form['field_r14']['und']['0']['value']['#size'] = '2';      
      $form['field_a01']['und']['0']['value']['#title'] = '';
      $form['field_a01']['und']['0']['value']['#size'] = '2';
      $form['field_a02']['und']['0']['value']['#title'] = '';
      $form['field_a02']['und']['0']['value']['#size'] = '2';      
      $form['field_a03']['und']['0']['value']['#title'] = '';
      $form['field_a03']['und']['0']['value']['#size'] = '2';
      $form['field_a03']['#disabled'] = TRUE;      
      $form['field_a04']['und']['0']['value']['#title'] = '';
      $form['field_a04']['und']['0']['value']['#size'] = '2';
      $form['field_a04']['#disabled'] = TRUE;      
      $form['field_a05']['und']['0']['value']['#title'] = '';
      $form['field_a05']['und']['0']['value']['#size'] = '2';
      $form['field_a06']['und']['0']['value']['#title'] = '';
      $form['field_a06']['und']['0']['value']['#size'] = '2';
      $form['field_a07']['und']['0']['value']['#title'] = '';
      $form['field_a07']['und']['0']['value']['#size'] = '2';
      $form['field_a08']['und']['0']['value']['#title'] = '';
      $form['field_a08']['und']['0']['value']['#size'] = '2';
      $form['field_a09']['und']['0']['value']['#title'] = '';
      $form['field_a09']['und']['0']['value']['#size'] = '2';
      $form['field_a10']['und']['0']['value']['#title'] = '';
      $form['field_a10']['und']['0']['value']['#size'] = '2';
      $form['field_a10']['#disabled'] = TRUE;
      $form['field_a11']['und']['0']['value']['#title'] = '';
      $form['field_a11']['und']['0']['value']['#size'] = '2';
      $form['field_a11']['#disabled'] = TRUE;
      $form['field_a12']['und']['0']['value']['#title'] = '';
      $form['field_a12']['und']['0']['value']['#size'] = '2';
      $form['field_a13']['und']['0']['value']['#title'] = '';
      $form['field_a13']['und']['0']['value']['#size'] = '2';
      $form['field_a14']['und']['0']['value']['#title'] = '';
      $form['field_a14']['und']['0']['value']['#size'] = '2';
      $form['field_s01']['und']['0']['value']['#title'] = '';
      $form['field_s01']['und']['0']['value']['#size'] = '2';
      $form['field_s02']['und']['0']['value']['#title'] = '';
      $form['field_s02']['und']['0']['value']['#size'] = '2';
      $form['field_s03']['und']['0']['value']['#title'] = '';
      $form['field_s03']['und']['0']['value']['#size'] = '2';
      $form['field_s03']['#disabled'] = TRUE;
      $form['field_s04']['und']['0']['value']['#title'] = '';
      $form['field_s04']['und']['0']['value']['#size'] = '2';
      $form['field_s04']['#disabled'] = TRUE;
      $form['field_s05']['und']['0']['value']['#title'] = '';
      $form['field_s05']['und']['0']['value']['#size'] = '2';
      $form['field_s06']['und']['0']['value']['#title'] = '';
      $form['field_s06']['und']['0']['value']['#size'] = '2';
      $form['field_s07']['und']['0']['value']['#title'] = '';
      $form['field_s07']['und']['0']['value']['#size'] = '2';
      $form['field_s08']['und']['0']['value']['#title'] = '';
      $form['field_s08']['und']['0']['value']['#size'] = '2';
      $form['field_s09']['und']['0']['value']['#title'] = '';
      $form['field_s09']['und']['0']['value']['#size'] = '2';
      $form['field_s10']['und']['0']['value']['#title'] = '';
      $form['field_s10']['und']['0']['value']['#size'] = '2';
      $form['field_s10']['#disabled'] = TRUE;
      $form['field_s11']['und']['0']['value']['#title'] = '';
      $form['field_s11']['und']['0']['value']['#size'] = '2';
      $form['field_s11']['#disabled'] = TRUE;
      $form['field_s12']['und']['0']['value']['#title'] = '';
      $form['field_s12']['und']['0']['value']['#size'] = '2';
      $form['field_s13']['und']['0']['value']['#title'] = '';
      $form['field_s13']['und']['0']['value']['#size'] = '2';
      $form['field_s14']['und']['0']['value']['#title'] = '';
      $form['field_s14']['und']['0']['value']['#size'] = '2';
      $form['field_t01']['und']['0']['value']['#title'] = '';
      $form['field_t01']['und']['0']['value']['#size'] = '2';
      $form['field_t02']['und']['0']['value']['#title'] = '';
      $form['field_t02']['und']['0']['value']['#size'] = '2';
      $form['field_t03']['und']['0']['value']['#title'] = '';
      $form['field_t03']['und']['0']['value']['#size'] = '2';
      $form['field_t03']['#disabled'] = TRUE;
      $form['field_t04']['und']['0']['value']['#title'] = '';
      $form['field_t04']['und']['0']['value']['#size'] = '2';
      $form['field_t04']['#disabled'] = TRUE;
      $form['field_t05']['und']['0']['value']['#title'] = '';
      $form['field_t05']['und']['0']['value']['#size'] = '2';
      $form['field_t06']['und']['0']['value']['#title'] = '';
      $form['field_t06']['und']['0']['value']['#size'] = '2';
      $form['field_t07']['und']['0']['value']['#title'] = '';
      $form['field_t07']['und']['0']['value']['#size'] = '2';
      $form['field_t08']['und']['0']['value']['#title'] = '';
      $form['field_t08']['und']['0']['value']['#size'] = '2';
      $form['field_t09']['und']['0']['value']['#title'] = '';
      $form['field_t09']['und']['0']['value']['#size'] = '2';
      $form['field_t10']['und']['0']['value']['#title'] = '';
      $form['field_t10']['und']['0']['value']['#size'] = '2';
      $form['field_t10']['#disabled'] = TRUE;
      $form['field_t11']['und']['0']['value']['#title'] = '';
      $form['field_t11']['und']['0']['value']['#size'] = '2';
      $form['field_t11']['#disabled'] = TRUE;
      $form['field_t12']['und']['0']['value']['#title'] = '';
      $form['field_t12']['und']['0']['value']['#size'] = '2';
      $form['field_t13']['und']['0']['value']['#title'] = '';
      $form['field_t13']['und']['0']['value']['#size'] = '2';
      $form['field_t14']['und']['0']['value']['#title'] = '';
      $form['field_t14']['und']['0']['value']['#size'] = '2';
      $form['field_grant_01_ref']['und']['#title'] = '';
      $form['field_grant_01_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_01_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_02_ref']['und']['#title'] = '';
      $form['field_grant_02_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_02_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_03_ref']['und']['#title'] = '';
      $form['field_grant_03_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_03_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_04_ref']['und']['#title'] = '';
      $form['field_grant_04_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_04_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_05_ref']['und']['#title'] = '';
      $form['field_grant_05_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_05_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_06_ref']['und']['#title'] = '';
      $form['field_grant_06_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_06_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_07_ref']['und']['#title'] = '';
      $form['field_grant_07_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_07_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_08_ref']['und']['#title'] = '';
      $form['field_grant_08_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_08_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_09_ref']['und']['#title'] = '';
      $form['field_grant_09_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_09_perc']['und']['0']['value']['#size'] = '5';
      $form['field_grant_10_ref']['und']['#title'] = '';
      $form['field_grant_10_perc']['und']['0']['value']['#title'] = '';
      $form['field_grant_10_perc']['und']['0']['value']['#size'] = '5';
      $form['field_ts_grant_total']['und']['0']['value']['#title'] = '';
      $form['field_ts_grant_total']['und']['0']['value']['#size'] = '5';

/*
      if (!empty($form_state['values']['field_r02'])) {
    $form['field_t02']['#default_value'] = 'new';
  }
*/



    // When employee approval field is 0, node has not yet been saved.
    if ($form['field_employee_approval']['und']['#default_value'] == 0) {
      $form['field_r01']['und']['0']['value']['#default_value'] = '8';
      $form['field_r02']['und']['0']['value']['#default_value'] = '8';
      $form['field_r03']['und']['0']['value']['#default_value'] = '0';
      $form['field_r04']['und']['0']['value']['#default_value'] = '0';
      $form['field_r05']['und']['0']['value']['#default_value'] = '8';
      $form['field_r06']['und']['0']['value']['#default_value'] = '8';
      $form['field_r07']['und']['0']['value']['#default_value'] = '8';
      $form['field_r08']['und']['0']['value']['#default_value'] = '8';
      $form['field_r09']['und']['0']['value']['#default_value'] = '8';
      $form['field_r10']['und']['0']['value']['#default_value'] = '0';
      $form['field_r11']['und']['0']['value']['#default_value'] = '0';
      $form['field_r12']['und']['0']['value']['#default_value'] = '8';
      $form['field_r13']['und']['0']['value']['#default_value'] = '8';
      $form['field_r14']['und']['0']['value']['#default_value'] = '8';
      $form['field_a01']['und']['0']['value']['#default_value'] = '0';
      $form['field_a02']['und']['0']['value']['#default_value'] = '0';
      $form['field_a03']['und']['0']['value']['#default_value'] = '0';
      $form['field_a04']['und']['0']['value']['#default_value'] = '0';
      $form['field_a05']['und']['0']['value']['#default_value'] = '0';
      $form['field_a06']['und']['0']['value']['#default_value'] = '0';
      $form['field_a07']['und']['0']['value']['#default_value'] = '0';
      $form['field_a08']['und']['0']['value']['#default_value'] = '0';
      $form['field_a09']['und']['0']['value']['#default_value'] = '0';
      $form['field_a10']['und']['0']['value']['#default_value'] = '0';
      $form['field_a11']['und']['0']['value']['#default_value'] = '0';
      $form['field_a12']['und']['0']['value']['#default_value'] = '0';
      $form['field_a13']['und']['0']['value']['#default_value'] = '0';
      $form['field_a14']['und']['0']['value']['#default_value'] = '0';
      $form['field_s01']['und']['0']['value']['#default_value'] = '0';
      $form['field_s02']['und']['0']['value']['#default_value'] = '0';
      $form['field_s03']['und']['0']['value']['#default_value'] = '0';
      $form['field_s04']['und']['0']['value']['#default_value'] = '0';
      $form['field_s05']['und']['0']['value']['#default_value'] = '0';
      $form['field_s06']['und']['0']['value']['#default_value'] = '0';
      $form['field_s07']['und']['0']['value']['#default_value'] = '0';
      $form['field_s08']['und']['0']['value']['#default_value'] = '0';
      $form['field_s09']['und']['0']['value']['#default_value'] = '0';
      $form['field_s10']['und']['0']['value']['#default_value'] = '0';
      $form['field_s11']['und']['0']['value']['#default_value'] = '0';
      $form['field_s12']['und']['0']['value']['#default_value'] = '0';
      $form['field_s13']['und']['0']['value']['#default_value'] = '0';
      $form['field_s14']['und']['0']['value']['#default_value'] = '0';
      $form['field_t01']['und']['0']['value']['#default_value'] = '8';
      $form['field_t02']['und']['0']['value']['#default_value'] = '8';
      $form['field_t03']['und']['0']['value']['#default_value'] = '0';
      $form['field_t04']['und']['0']['value']['#default_value'] = '0';
      $form['field_t05']['und']['0']['value']['#default_value'] = '8';
      $form['field_t06']['und']['0']['value']['#default_value'] = '8';
      $form['field_t07']['und']['0']['value']['#default_value'] = '8';
      $form['field_t08']['und']['0']['value']['#default_value'] = '8';
      $form['field_t09']['und']['0']['value']['#default_value'] = '8';
      $form['field_t10']['und']['0']['value']['#default_value'] = '0';
      $form['field_t11']['und']['0']['value']['#default_value'] = '0';
      $form['field_t12']['und']['0']['value']['#default_value'] = '8';
      $form['field_t13']['und']['0']['value']['#default_value'] = '8';
      $form['field_t14']['und']['0']['value']['#default_value'] = '8';
      
      // @todo - brad put them here...
      
      $form['actions']['submit']['#value'] = t('Save and Send');
    }
    
    // Check the status field to determine progress of node
    $status = $form['field_ts_status']['und']['#default_value'][0];
    if ( $status == '1') {
      
    } elseif (($status == '2') || ($status == '3')) {
      $form['actions']['submit']['#value'] = t('Approve');
    } elseif ($status == '4') {
      $form['actions']['submit']['#value'] = t('Save');
    }
    
    if (($status == '1') && ($form['field_employee_approval']['und']['#default_value'] == 0)) {
      // First Stage — Node is being created...not yet saved.
      /*
$form['field_supervisor_approval']['#disabled'] = TRUE;
      $form['field_sup_approve_date']['#disabled'] = TRUE;
*/
    }
    
    if ((($status == '1') && ($form['field_employee_approval']['und']['#default_value'] == 1))  || (!($status == '1') && !($form['field_employee_approval']['und']['#default_value'] == 0) && ((!in_array('payroll first admin', array_values($user->roles))) || (!in_array('payroll final admin', array_values($user->roles))) || (!in_array('payroll administrator', array_values($user->roles)))))) {
      // Second Stage — Node has been created. Supervisor not approved.
      $form['field_r01']['#disabled'] = TRUE;
      $form['field_r02']['#disabled'] = TRUE;
      $form['field_r03']['#disabled'] = TRUE;
      $form['field_r04']['#disabled'] = TRUE;
      $form['field_r05']['#disabled'] = TRUE;
      $form['field_r06']['#disabled'] = TRUE;
      $form['field_r07']['#disabled'] = TRUE;
      $form['field_r08']['#disabled'] = TRUE;
      $form['field_r09']['#disabled'] = TRUE;
      $form['field_r10']['#disabled'] = TRUE;
      $form['field_r11']['#disabled'] = TRUE;
      $form['field_r12']['#disabled'] = TRUE;
      $form['field_r13']['#disabled'] = TRUE;
      $form['field_r14']['#disabled'] = TRUE;
      $form['field_a01']['#disabled'] = TRUE;
      $form['field_a02']['#disabled'] = TRUE;
      $form['field_a03']['#disabled'] = TRUE;
      $form['field_a04']['#disabled'] = TRUE;
      $form['field_a05']['#disabled'] = TRUE;
      $form['field_a06']['#disabled'] = TRUE;
      $form['field_a07']['#disabled'] = TRUE;
      $form['field_a08']['#disabled'] = TRUE;
      $form['field_a09']['#disabled'] = TRUE;
      $form['field_a10']['#disabled'] = TRUE;
      $form['field_a11']['#disabled'] = TRUE;
      $form['field_a12']['#disabled'] = TRUE;
      $form['field_a13']['#disabled'] = TRUE;
      $form['field_a14']['#disabled'] = TRUE;
      $form['field_s01']['#disabled'] = TRUE;
      $form['field_s02']['#disabled'] = TRUE;
      $form['field_s03']['#disabled'] = TRUE;
      $form['field_s04']['#disabled'] = TRUE;
      $form['field_s05']['#disabled'] = TRUE;
      $form['field_s06']['#disabled'] = TRUE;
      $form['field_s07']['#disabled'] = TRUE;
      $form['field_s08']['#disabled'] = TRUE;
      $form['field_s09']['#disabled'] = TRUE;
      $form['field_s10']['#disabled'] = TRUE;
      $form['field_s11']['#disabled'] = TRUE;
      $form['field_s12']['#disabled'] = TRUE;
      $form['field_s13']['#disabled'] = TRUE;
      $form['field_s14']['#disabled'] = TRUE;
      $form['field_t01']['#disabled'] = TRUE;
      $form['field_t02']['#disabled'] = TRUE;
      $form['field_t03']['#disabled'] = TRUE;
      $form['field_t04']['#disabled'] = TRUE;
      $form['field_t05']['#disabled'] = TRUE;
      $form['field_t06']['#disabled'] = TRUE;
      $form['field_t07']['#disabled'] = TRUE;
      $form['field_t08']['#disabled'] = TRUE;
      $form['field_t09']['#disabled'] = TRUE;
      $form['field_t10']['#disabled'] = TRUE;
      $form['field_t11']['#disabled'] = TRUE;
      $form['field_t12']['#disabled'] = TRUE;
      $form['field_t13']['#disabled'] = TRUE;
      $form['field_t14']['#disabled'] = TRUE;
      $form['field_grant_01_ref']['#disabled'] = TRUE;
      $form['field_grant_02_ref']['#disabled'] = TRUE;
      $form['field_grant_03_ref']['#disabled'] = TRUE;
      $form['field_grant_04_ref']['#disabled'] = TRUE;
      $form['field_grant_05_ref']['#disabled'] = TRUE;
      $form['field_grant_06_ref']['#disabled'] = TRUE;
      $form['field_grant_07_ref']['#disabled'] = TRUE;
      $form['field_grant_08_ref']['#disabled'] = TRUE;
      $form['field_grant_09_ref']['#disabled'] = TRUE;
      $form['field_grant_10_ref']['#disabled'] = TRUE;
      $form['field_grant_01_perc']['#disabled'] = TRUE;
      $form['field_grant_02_perc']['#disabled'] = TRUE;
      $form['field_grant_03_perc']['#disabled'] = TRUE;
      $form['field_grant_04_perc']['#disabled'] = TRUE;
      $form['field_grant_05_perc']['#disabled'] = TRUE;
      $form['field_grant_06_perc']['#disabled'] = TRUE;
      $form['field_grant_07_perc']['#disabled'] = TRUE;
      $form['field_grant_08_perc']['#disabled'] = TRUE;
      $form['field_grant_09_perc']['#disabled'] = TRUE;
      $form['field_grant_10_perc']['#disabled'] = TRUE;
      $form['field_ts_grant_total']['#disabled'] = TRUE;
    }
    
    if ($status == '2') {
      
    }
    
    
      
    // That's it. Stop checking form ids.
    break;
  }
}


/**
 * Implements hook_theme_registry_alter()
**/
function cehs_ts_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'cehs_ts');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _cehs_ts_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
*/
function _cehs_ts_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}



/**
 * Implements hook_theme().
 *
 * @todo - Specify the use of a template file for each node add/edit form.
 */
function cehs_ts_theme() {
    return array(
        'ts_biweekly_node_form' => array(
            'template' => 'ts-biweekly-node-form',
            'render element' => 'form',
            'path' => drupal_get_path('module', 'cehs_ts').'/theme'
        ),
        'ts_monthly_node_form' => array(
            'template' => 'ts-monthly-node-form',
            'render element' => 'form',
            'path' => drupal_get_path('module', 'cehs_ts').'/theme'
        ),
        'ts_semimonthly_node_form' => array(
            'template' => 'ts-semimonthly-node-form',
            'render element' => 'form',
            'path' => drupal_get_path('module', 'cehs_ts').'/theme'
        ),
    );
}


/**
 * Implements hook_init().
 */
function cehs_ts_init() {
  drupal_add_js(drupal_get_path('module', 'cehs_ts').'/js/biweekly.js', 'file');
  drupal_add_js(drupal_get_path('module', 'cehs_ts').'/js/jquery.validate.js', 'file');
  drupal_add_css(drupal_get_path('module', 'cehs_ts').'/css/cehs_ts.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}




/* module_load_include('inc', 'cehs_ts', 'cehs_ts_node_form_alter'); */
